//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oh_lala_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Event = new HashSet<Event>();
            this.Event1 = new HashSet<Event>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<Event> Event1 { get; set; }
    }
}
