//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oh_lala_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventEntities : DbContext
    {
        public EventEntities()
            : base("name=EventEntities")
        {
        }

        public EventEntities(string connStringName)
            : base("name=" + connStringName)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Event> Event { get; set; }
        public DbSet<Image> Image { get; set; }
        public DbSet<Service> Service { get; set; }
        public DbSet<TypeEvent> TypeEvent { get; set; }
        public DbSet<TypeService> TypeService { get; set; }
    }
}
