//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oh_lala_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeService
    {
        public TypeService()
        {
            this.Service = new HashSet<Service>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Service> Service { get; set; }
    }
}
